Initial init.d support

diff --git a/templates/default/wildfly-init-debian.sh.erb b/templates/default/wildfly-init-debian.sh.erb
--- a/templates/default/wildfly-init-debian.sh.erb
+++ b/templates/default/wildfly-init-debian.sh.erb
@@ -13,15 +13,12 @@
 # Default-Start:        2 3 4 5
 # Default-Stop:         0 1 6
 # Short-Description:    WildFly Application Server
-# Description:          Provide WildFly startup/shutdown script
+# Description:          WildFly startup/shutdown script
 ### END INIT INFO
-#
-# Managed by Chef - local changes may be overwritten
-#
 
-NAME=wildfly
+NAME=$(readlink -f ${0} | xargs basename)
 DESC="WildFly Application Server"
-DEFAULT="/etc/default/wildfly.conf"
+DEFAULT="/etc/default/$NAME"
 
 # Check privileges
 if [ `id -u` -ne 0 ]; then
@@ -35,6 +32,7 @@ if [ -r /etc/default/locale ]; then
 	export LANG
 fi
 
+# Source function library.
 . /lib/lsb/init-functions
 
 if [ -r /etc/default/rcS ]; then
@@ -62,7 +60,7 @@ fi
 
 # Location of wildfly
 if [ -z "$JBOSS_HOME" ]; then
-	JBOSS_HOME="/opt/wildfly"
+	JBOSS_HOME="/opt/$NAME"
 fi
 export JBOSS_HOME
 
@@ -103,6 +101,7 @@ if [ "$JBOSS_MODE" = "standalone" ]; then
 	if [ -z "$JBOSS_CONFIG" ]; then
 		JBOSS_CONFIG=standalone.xml
 	fi
+	JBOSS_MARKERFILE="$JBOSS_HOME/standalone/tmp/startup-marker"
 else
 	JBOSS_SCRIPT="$JBOSS_HOME/bin/domain.sh"
 	if [ -z "$JBOSS_DOMAIN_CONFIG" ]; then
@@ -111,6 +110,7 @@ else
 	if [ -z "$JBOSS_HOST_CONFIG" ]; then
 		JBOSS_HOST_CONFIG=host.xml
 	fi
+	JBOSS_MARKERFILE="$JBOSS_HOME/domain/tmp/startup-marker"
 fi
 
 # Check startup file
@@ -143,7 +143,7 @@ fi
 export JBOSS_CONSOLE_LOG
 
 # Location to set the pid file
-JBOSS_PIDFILE="/var/run/$NAME/$NAME.pid"
+JBOSS_PIDFILE="/var/run/wildfly/$NAME.pid"
 export JBOSS_PIDFILE
 
 # Launch wildfly in background
@@ -165,41 +165,52 @@ case "$1" in
 		mkdir -p $(dirname "$JBOSS_CONSOLE_LOG")
 		chown $JBOSS_USER $(dirname "$JBOSS_PIDFILE") || true
 		cat /dev/null > "$JBOSS_CONSOLE_LOG"
+		currenttime=$(date +%s%N | cut -b1-13)
 
 		if [ "$JBOSS_MODE" = "standalone" ]; then
 			start-stop-daemon --start --user "$JBOSS_USER" \
 			--chuid "$JBOSS_USER" --chdir "$JBOSS_HOME" --pidfile "$JBOSS_PIDFILE" \
-			--exec "$JBOSS_SCRIPT" -- -c $JBOSS_CONFIG >> "$JBOSS_CONSOLE_LOG" 2>&1 &
+			--exec "$JBOSS_SCRIPT" -- -c $JBOSS_CONFIG $JBOSS_OPTS >> "$JBOSS_CONSOLE_LOG" 2>&1 &
 		else
 			start-stop-daemon --start --user "$JBOSS_USER" \
 			--chuid "$JBOSS_USER" --chdir "$JBOSS_HOME" --pidfile "$JBOSS_PIDFILE" \
 			--exec "$JBOSS_SCRIPT" -- --domain-config=$JBOSS_DOMAIN_CONFIG \
-			--host-config=$JBOSS_HOST_CONFIG >> "$JBOSS_CONSOLE_LOG" 2>&1 &
+			--host-config=$JBOSS_HOST_CONFIG $JBOSS_OPTS >> "$JBOSS_CONSOLE_LOG" 2>&1 &
 		fi
 
 		count=0
-		launched=0
 		until [ $count -gt $STARTUP_WAIT ]
 		do
-			grep 'JBAS015874:' "$JBOSS_CONSOLE_LOG" > /dev/null
-			if [ $? -eq 0 ] ; then
-				launched=1
-				break
-			fi
 			sleep 1
 			count=$((count + 1));
+			if [ -f "$JBOSS_MARKERFILE" ]; then
+				markerfiletimestamp=$(grep -o '[0-9]*' "$JBOSS_MARKERFILE") > /dev/null
+				if [ "$markerfiletimestamp" -gt "$currenttime" ] ; then
+					grep -i 'success:' "$JBOSS_MARKERFILE" > /dev/null
+					if [ $? -eq 0 ]; then
+						log_end_msg 0
+						exit 0
+					fi
+					grep -i 'error:' "$JBOSS_MARKERFILE" > /dev/null
+					if [ $? -eq 0 ]; then
+						log_end_msg 255
+						log_warning_msg "$DESC started with errors, please see server log for details."
+						exit 0
+					fi
+				fi
+			fi
 		done
 
 		if check_status; then
-			log_end_msg 0
+			log_end_msg 255
+			log_warning_msg "$DESC hasn't started within the timeout allowed."
+			exit 0
 		else
 			log_end_msg 1
+			log_failure_msg "$DESC failed to start within the timeout allowed."
+			exit 1
 		fi
 
-		if [ $launched -eq 0 ]; then
-			log_warning_msg "$DESC hasn't started within the timeout allowed"
-			log_warning_msg "please review file \"$JBOSS_CONSOLE_LOG\" to see the status of the service"
-		fi
 	elif [ $status_start -eq 1 ]; then
 		log_failure_msg "$DESC is not running but the pid file exists"
 		exit 1
@@ -214,29 +225,21 @@ case "$1" in
 		read kpid < "$JBOSS_PIDFILE"
 		log_daemon_msg "Stopping $DESC" "$NAME"
 
-		start-stop-daemon --start --chuid "$JBOSS_USER" \
-		--exec "$JBOSS_CLI" -- --connect --command=:shutdown \
+		children_pids=$(pgrep -P $kpid)
+
+		start-stop-daemon --stop --quiet --pidfile "$JBOSS_PIDFILE" \
+		--user "$JBOSS_USER" --retry=TERM/$SHUTDOWN_WAIT/KILL/5 \
 		>/dev/null 2>&1
 
-		if [ $? -eq 1 ]; then
-			kill -15 $kpid
+		if [ $? -eq 2 ]; then
+			log_failure_msg "$DESC can't be stopped"
+			exit 1
 		fi
 
-		count=0
-		until [ $count -gt $SHUTDOWN_WAIT ]
-		do
-			check_status
-			if [ $? -eq 3 ]; then
-				break
-			fi
-			sleep 1
-			count=$((count + 1));
+		for child in $children_pids; do
+			/bin/kill -9 $child >/dev/null 2>&1
 		done
 
-		if [ $count -gt $SHUTDOWN_WAIT ]; then
-			kill -9 $kpid
-		fi
-		
 		log_end_msg 0
 	elif [ $status_stop -eq 1 ]; then
 		log_action_msg "$DESC is not running but the pid file exists, cleaning up"
